#!/usr/bin/env python3
"""Turn matlab/galleryFigures.m into _data/gallery.yml, the gallery of the site.

    tools/gallery-data.py

Every cell "%% <name>" of the script is one entry: its figure is
figures/gallery/<name>.png, its "%#page", "%#title" and "%#labels" lines
describe it, and its visible lines (not ending in
"% hide") are its code. The labels are the filters of the gallery. Rerun it
after editing the script.
"""
import importlib.util
import os
import re

import yaml

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT = os.path.join(SITE, "matlab", "galleryFigures.m")
OUT = os.path.join(SITE, "_data", "gallery.yml")

# the highlighting of the code card
spec = importlib.util.spec_from_file_location("hero", os.path.join(SITE, "tools", "hero-code.py"))
hero = importlib.util.module_from_spec(spec)
spec.loader.exec_module(hero)


def main():
    with open(SCRIPT) as f:
        text = f.read()
    variables = hero.assigned(text)
    entries = []
    for block in re.split(r"^%% ", text, flags=re.M)[1:]:
        head, _, body = block.partition("\n")
        name = head.strip()
        if name == "galleryFigures":
            continue
        meta, shown = {}, []
        for line in body.rstrip().split("\n"):
            m = re.match(r"%#(\w+)\s+(.*)", line)
            if m:
                meta[m.group(1)] = m.group(2).strip()
            elif not re.search(r"%\s*hide\s*$", line):
                shown.append(line.rstrip())
        while shown and not shown[-1]:
            shown.pop()
        if not os.path.exists(os.path.join(SITE, "figures", "gallery", name + ".png")):
            raise FileNotFoundError(f"Render galleryFigures.m first: missing {name}.png")
        entries.append({"figure": f"figures/gallery/{name}.png", "page": meta["page"],
                        "title": meta["title"],
                        "labels": [l.strip() for l in meta.get("labels", "").split(",") if l.strip()],
                        "code": "\n".join(hero.highlight(l, variables) for l in shown)})
    with open(OUT, "w") as f:
        f.write("# generated by tools/gallery-data.py from matlab/galleryFigures.m - do not edit\n")
        yaml.safe_dump({"figures": entries}, f, sort_keys=False, allow_unicode=True, width=1000)
    print(f"{len(entries)} figures -> {os.path.relpath(OUT, SITE)}")
    labels = {}
    for e in entries:
        for l in e["labels"]:
            labels[l] = labels.get(l, 0) + 1
    print("  labels:", ", ".join(f"{k} {v}" for k, v in labels.items()))


if __name__ == "__main__":
    main()
