#!/usr/bin/env python3
"""Turn matlab/galleryFigures.m into _data/gallery.yml, the gallery of the site.

    tools/gallery-data.py

Every cell "%% <name>" of the script is one entry: its figure is
figures/gallery/<name>.png, its "%#page", "%#title" and "%#text" lines
describe it, and its visible lines (not ending in "% hide") are its code. The
section and chapter of the page are read from the documentation sidebar, so
the gallery can be filtered by chapter. Rerun it after editing the script.
"""
import importlib.util
import os
import re

import yaml

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT = os.path.join(SITE, "matlab", "galleryFigures.m")
OUT = os.path.join(SITE, "_data", "gallery.yml")

# the highlighting of the code card
spec = importlib.util.spec_from_file_location("hero", os.path.join(SITE, "tools", "hero-code.py"))
hero = importlib.util.module_from_spec(spec)
spec.loader.exec_module(hero)


def places():
    """page -> (section, chapter title) from the documentation sidebar"""
    with open(os.path.join(SITE, "_data", "sidebars", "documentation_sidebar.yml")) as f:
        side = yaml.safe_load(f)
    found = {}
    for sec in side["entries"][0]["folders"]:
        for ch in (sec.get("folderitems") or {}).get("subfolders") or []:
            for pg in ch.get("subfolderitems") or []:
                found[pg["url"].strip("/")[:-5]] = (sec["title"], ch["title"])
    with open(os.path.join(SITE, "_data", "docmap.yml")) as f:
        cases = yaml.safe_load(f).get("case_studies", {})
    chapters = {ch["url"].strip("/")[:-5]: (sec["title"], ch["title"])
                for sec in side["entries"][0]["folders"]
                for ch in (sec.get("folderitems") or {}).get("subfolders") or []}
    for key, pages in cases.items():
        for c in pages:
            found.setdefault(c["page"], chapters.get(key, ("Tasks", "")))
    return found


def main():
    with open(SCRIPT) as f:
        text = f.read()
    variables = hero.assigned(text)
    where = places()
    entries = []
    for block in re.split(r"^%% ", text, flags=re.M)[1:]:
        head, _, body = block.partition("\n")
        name = head.strip()
        if name == "galleryFigures":
            continue
        meta, shown = {}, []
        for line in body.rstrip().split("\n"):
            m = re.match(r"%#(\w+)\s+(.*)", line)
            if m:
                meta[m.group(1)] = m.group(2).strip()
            elif not re.search(r"%\s*hide\s*$", line):
                shown.append(line.rstrip())
        while shown and not shown[-1]:
            shown.pop()
        if not os.path.exists(os.path.join(SITE, "figures", "gallery", name + ".png")):
            print(f"  no figure for {name}, left out")
            continue
        section, chapter = where.get(meta["page"], ("", ""))
        entries.append({"figure": f"figures/gallery/{name}.png", "page": meta["page"],
                        "title": meta["title"], "text": meta["text"],
                        "section": section, "chapter": chapter,
                        "code": "\n".join(hero.highlight(l, variables) for l in shown)})
    with open(OUT, "w") as f:
        f.write("# generated by tools/gallery-data.py from matlab/galleryFigures.m - do not edit\n")
        yaml.safe_dump({"figures": entries}, f, sort_keys=False, allow_unicode=True, width=1000)
    print(f"{len(entries)} figures -> {os.path.relpath(OUT, SITE)}")
    for e in entries:
        print(f"  {e['page']}: {e['section']} / {e['chapter']}")


if __name__ == "__main__":
    main()
