#!/usr/bin/env python3
"""Turn matlab/heroFigures.m into _data/hero.yml, the code card of the homepage.

    tools/hero-code.py

Every cell "%% <tab name>" of the script becomes one tab. Its visible lines
(those not ending in "% hide") are the code shown, highlighted here into HTML;
a line "%show <code>" is shown but not run; the line "%#captions a | b" names the figures that matlab/heroExport.m wrote
to figures/hero/<tab>_<n>.png. Run it after editing heroFigures.m, and rerun
the script in MATLAB when the code of a cell changed.
"""
import html
import os
import re

import yaml

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT = os.path.join(SITE, "matlab", "heroFigures.m")
OUT = os.path.join(SITE, "_data", "hero.yml")

# the export names of the cells, as heroExport is called in them
EXPORT = re.compile(r"heroExport\('([^']+)',(\d+)\)")
TOKEN = re.compile(r"""
    (?P<comment>%.*$)
  | (?P<string>(?<![\w\)\]\}'.])'[^'\n]*')
  | (?P<call>[A-Za-z]\w*(?:\.[A-Za-z]\w*)*)(?=\()
  | (?P<other>.)
""", re.X)


def highlight(line, variables):
    out = []
    for m in TOKEN.finditer(line):
        text = html.escape(m.group(0), quote=False)
        if m.lastgroup == "comment":
            out.append(f'<span class="c">{text}</span>')
        elif m.lastgroup == "string":
            out.append(f'<span class="s">{text}</span>')
        elif m.lastgroup == "call" and text.split(".")[0] in variables:
            # a method of a variable, or indexing into one
            *obj, name = text.split(".")
            out.append(".".join(obj) + f'.<span class="k">{name}</span>' if obj else text)
        elif m.lastgroup == "call":
            out.append(f'<span class="k">{text}</span>')
        else:
            out.append(text)
    return "".join(out)


def assigned(text):
    """The names the script assigns to, [a,b] = ... included."""
    names = set()
    for lhs in re.findall(r"^\s*(\[[^\]]*\]|[A-Za-z]\w*)\s*=(?!=)", text, flags=re.M):
        names |= set(re.findall(r"[A-Za-z]\w*", lhs))
    return names


def cells():
    with open(SCRIPT) as f:
        text = f.read()
    for block in re.split(r"^%% ", text, flags=re.M)[1:]:
        head, _, body = block.partition("\n")
        if head.strip() == "heroFigures":
            continue
        yield head.strip(), body


def main():
    with open(SCRIPT) as f:
        variables = assigned(f.read())
    steps = []
    for name, body in cells():
        lines = body.rstrip().split("\n")
        captions = []
        shown = []
        exports = []
        for line in lines:
            if line.startswith("%#captions"):
                captions = [c.strip() for c in line[len("%#captions"):].split("|")]
                continue
            if line.startswith("%show "):
                shown.append(line[len("%show "):].rstrip())
                continue
            exports += EXPORT.findall(line)
            if re.search(r"%\s*hide\s*$", line):
                continue
            shown.append(line.rstrip())
        while shown and not shown[-1]:
            shown.pop()
        figures = [{"file": f"figures/hero/{s}_{n}.png", "caption": c}
                   for (s, n), c in zip(exports, captions)
                   if os.path.exists(os.path.join(SITE, "figures", "hero", f"{s}_{n}.png"))]
        steps.append({"name": name, "code": "\n".join(highlight(l, variables) for l in shown), "figures": figures})
    with open(OUT, "w") as f:
        f.write("# generated by tools/hero-code.py from matlab/heroFigures.m - do not edit\n")
        yaml.safe_dump({"steps": steps}, f, sort_keys=False, allow_unicode=True, width=1000)
    print(f"{len(steps)} steps -> {os.path.relpath(OUT, SITE)}")
    for s in steps:
        print(f"  {s['name']}: {s['code'].count(chr(10)) + 1} lines, {len(s['figures'])} figures")


if __name__ == "__main__":
    main()
